This notebook shows some simple demonstrations of using the functions in the starter module to create numpy arrays that will be fed to cellular automata. The examples use relatively short arrays, but typically I run cellular automata with a starter of at least 32 elements, often two thousand or more.

In [1]:
import numpy as np
import starter as st

## Creation functions

Make a random binary starter that's sixteen pixels wide.

In [2]:
st.random(k=2, width=16)

array([1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1])

Make another random starter in ternary.

In [3]:
st.random(k=3, width=16)

array([2, 0, 2, 0, 0, 0, 2, 0, 1, 0, 2, 0, 1, 0, 1, 1])

It's often interesting to see how cellular automata react to an isolated one in a field of zeros.

In [4]:
st.impulse(16)

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

Numpy's element-wise array math makes variations very easy to generate. This code generates a three in a field of ones.

In [5]:
st.impulse(16) * 2 + 1

array([1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1])

Following numpy's terminology, the repeat function repeats each element of an array.

In [6]:
st.repeat([0,1,2], 3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

Numpy's tile function does some weird things to the array's axes, so this is a little more straightforward.

In [7]:
st.cycle([0,1,2], 3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

## Manipulation Functions



In [8]:
test = st.cycle([0,1,2], 3)
st.mirror(test)

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 2, 1, 0, 2, 1, 0, 2, 1, 0])

In [9]:
st.shuffle(test)

array([0, 2, 2, 1, 2, 1, 0, 0, 1])

## Combining

For example, make evenly spaced stripes:

In [10]:
st.cycle(st.repeat([0,0,1], 3), 2)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1])

Or a more mathematical approach to something similar:

In [11]:
test = st.repeat([0], 10)
test[0::3] = 1
st.repeat(test, 2)

array([1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1])